import { Candidate, Job, Stages } from "../types";

export const initialCandidate = (jobId: string): Candidate => ({
  id: `${Date.now()}`,
  name: "",
  grade: "",
  avatar: "",
  comment: "",
  contact: "",
  link: "",
  jobId,
  tags: "",
});

export const initialJob = (): Job => ({
  id: `${Date.now()}`,
  name: "",
  company: "",
  candidates: [
    { title: "Новые", type: Stages.new, list: [] },
    { title: "В работе", type: Stages.inProgress, list: [] },
    { title: "Прошли интервью", type: Stages.interviewed, list: [] },
    { title: "Оффер", type: Stages.offer, list: [] },
  ],
});

export const demoJobs: Job[] = [
  {
    id: "job1",
    name: "Senior React-Developer",
    company: "Сбербанк",
    candidates: [
      {
        title: "Новые",
        type: Stages.new,
        list: [
          {
            id: "1",
            jobId: "job1",
            name: "Rick Sanchez",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
            comment: "",
            tags: "Male,Alive ,",
            contact: "Citadel of Ricks",
            link: "https://rickandmortyapi.com/api/location/3",
          },
          {
            id: "2",
            jobId: "job1",
            name: "Morty Smith",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
            comment: "",
            tags: "Male,Alive ,",
            contact: "Citadel of Ricks",
            link: "https://rickandmortyapi.com/api/location/3",
          },
          {
            id: "3",
            jobId: "job1",
            name: "Summer Smith",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/3.jpeg",
            comment: "",
            tags: "Female,Alive ,",
            contact: "Earth (Replacement Dimension)",
            link: "https://rickandmortyapi.com/api/location/20",
          },
          {
            id: "4",
            jobId: "job1",
            name: "Beth Smith",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/4.jpeg",
            comment: "",
            tags: "Female,Alive ,",
            contact: "Earth (Replacement Dimension)",
            link: "https://rickandmortyapi.com/api/location/20",
          },
          {
            id: "5",
            jobId: "job1",
            name: "Jerry Smith",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/5.jpeg",
            comment: "",
            tags: "Male,Alive ,",
            contact: "Earth (Replacement Dimension)",
            link: "https://rickandmortyapi.com/api/location/20",
          },
        ],
      },
      {
        title: "В работе",
        type: Stages.inProgress,
        list: [
          {
            id: "7",
            jobId: "job1",
            name: "Abradolf Lincler",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/7.jpeg",
            comment: "",
            tags: "Male,unknown ,Genetic experiment",
            contact: "Testicle Monster Dimension",
            link: "https://rickandmortyapi.com/api/location/21",
          },
          {
            id: "8",
            jobId: "job1",
            name: "Adjudicator Rick",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/8.jpeg",
            comment: "",
            tags: "Male,Dead ,",
            contact: "Citadel of Ricks",
            link: "https://rickandmortyapi.com/api/location/3",
          },
          {
            id: "9",
            jobId: "job1",
            name: "Agency Director",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/9.jpeg",
            comment: "",
            tags: "Male,Dead ,",
            contact: "Earth (Replacement Dimension)",
            link: "https://rickandmortyapi.com/api/location/20",
          },
          {
            id: "10",
            jobId: "job1",
            name: "Alan Rails",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/10.jpeg",
            comment: "",
            tags: "Male,Dead ,Superhuman (Ghost trains summoner)",
            contact: "Worldender's lair",
            link: "https://rickandmortyapi.com/api/location/4",
          },
          {
            id: "11",
            jobId: "job1",
            name: "Albert Einstein",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/11.jpeg",
            comment: "",
            tags: "Male,Dead ,",
            contact: "Earth (Replacement Dimension)",
            link: "https://rickandmortyapi.com/api/location/20",
          },
        ],
      },
      {
        title: "Прошли интервью",
        type: Stages.interviewed,
        list: [
          {
            id: "13",
            jobId: "job1",
            name: "Alien Googah",
            grade: "Alien",
            avatar: "https://rickandmortyapi.com/api/character/avatar/13.jpeg",
            comment: "",
            tags: "unknown,unknown ,",
            contact: "Earth (Replacement Dimension)",
            link: "https://rickandmortyapi.com/api/location/20",
          },
          {
            id: "14",
            jobId: "job1",
            name: "Alien Morty",
            grade: "Alien",
            avatar: "https://rickandmortyapi.com/api/character/avatar/14.jpeg",
            comment: "",
            tags: "Male,unknown ,",
            contact: "Citadel of Ricks",
            link: "https://rickandmortyapi.com/api/location/3",
          },
          {
            id: "15",
            jobId: "job1",
            name: "Alien Rick",
            grade: "Alien",
            avatar: "https://rickandmortyapi.com/api/character/avatar/15.jpeg",
            comment: "",
            tags: "Male,unknown ,",
            contact: "Citadel of Ricks",
            link: "https://rickandmortyapi.com/api/location/3",
          },
          {
            id: "16",
            jobId: "job1",
            name: "Amish Cyborg",
            grade: "Alien",
            avatar: "https://rickandmortyapi.com/api/character/avatar/16.jpeg",
            comment: "",
            tags: "Male,Dead ,Parasite",
            contact: "Earth (Replacement Dimension)",
            link: "https://rickandmortyapi.com/api/location/20",
          },
          {
            id: "17",
            jobId: "job1",
            name: "Annie",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/17.jpeg",
            comment: "",
            tags: "Female,Alive ,",
            contact: "Anatomy Park",
            link: "https://rickandmortyapi.com/api/location/5",
          },
        ],
      },
      {
        title: "Оффер",
        type: Stages.offer,
        list: [
          {
            id: "19",
            jobId: "job1",
            name: "Antenna Rick",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/19.jpeg",
            comment: "",
            tags: "Male,unknown ,Human with antennae",
            contact: "unknown",
            link: "",
          },
          {
            id: "20",
            jobId: "job1",
            name: "Ants in my Eyes Johnson",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/20.jpeg",
            comment: "",
            tags: "Male,unknown ,Human with ants in his eyes",
            contact: "Interdimensional Cable",
            link: "https://rickandmortyapi.com/api/location/6",
          },
        ],
      },
    ],
  },
  {
    id: "job2",
    name: "Фронтенд-разработчик Vue",
    company: "Яндекс",
    candidates: [
      {
        title: "Новые",
        type: Stages.new,
        list: [
          {
            id: "22",
            jobId: "job2",
            name: "Rick Sanchez",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
            comment: "",
            tags: "Male,Alive ,",
            contact: "Citadel of Ricks",
            link: "https://rickandmortyapi.com/api/location/3",
          },
          {
            id: "33",
            jobId: "job2",
            name: "Morty Smith",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
            comment: "",
            tags: "Male,Alive ,",
            contact: "Citadel of Ricks",
            link: "https://rickandmortyapi.com/api/location/3",
          },
        ],
      },
      {
        title: "В работе",
        type: Stages.inProgress,
        list: [
          {
            id: "77",
            jobId: "job2",
            name: "Abradolf Lincler",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/7.jpeg",
            comment: "",
            tags: "Male,unknown ,Genetic experiment",
            contact: "Testicle Monster Dimension",
            link: "https://rickandmortyapi.com/api/location/21",
          },
          {
            id: "88",
            jobId: "job2",
            name: "Adjudicator Rick",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/8.jpeg",
            comment: "",
            tags: "Male,Dead ,",
            contact: "Citadel of Ricks",
            link: "https://rickandmortyapi.com/api/location/3",
          },
        ],
      },
      {
        title: "Прошли интервью",
        type: Stages.interviewed,
        list: [
          {
            id: "133",
            jobId: "job2",
            name: "Alien Googah",
            grade: "Alien",
            avatar: "https://rickandmortyapi.com/api/character/avatar/13.jpeg",
            comment: "",
            tags: "unknown,unknown ,",
            contact: "Earth (Replacement Dimension)",
            link: "https://rickandmortyapi.com/api/location/20",
          },
        ],
      },
      {
        title: "Оффер",
        type: Stages.offer,
        list: [
          {
            id: "199",
            jobId: "job2",
            name: "Antenna Rick",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/19.jpeg",
            comment: "",
            tags: "Male,unknown ,Human with antennae",
            contact: "unknown",
            link: "",
          },
        ],
      },
    ],
  },
  {
    id: "job3",
    name: "Middle React",
    company: "Ланит",
    candidates: [
      {
        title: "Новые",
        type: Stages.new,
        list: [
          {
            id: "32432",
            jobId: "job3",
            name: "Morty Smith",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
            comment: "",
            tags: "Male,Alive ,",
            contact: "Citadel of Ricks",
            link: "https://rickandmortyapi.com/api/location/3",
          },
        ],
      },
      {
        title: "В работе",
        type: Stages.inProgress,
        list: [
          {
            id: "7655",
            jobId: "job3",
            name: "Abradolf Lincler",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/7.jpeg",
            comment: "",
            tags: "Male,unknown ,Genetic experiment",
            contact: "Testicle Monster Dimension",
            link: "https://rickandmortyapi.com/api/location/21",
          },
          {
            id: "5465462",
            jobId: "job3",
            name: "Adjudicator Rick",
            grade: "Human",
            avatar: "https://rickandmortyapi.com/api/character/avatar/8.jpeg",
            comment: "",
            tags: "Male,Dead ,",
            contact: "Citadel of Ricks",
            link: "https://rickandmortyapi.com/api/location/3",
          },
        ],
      },
      {
        title: "Прошли интервью",
        type: Stages.interviewed,
        list: [
          {
            id: "132233",
            jobId: "job3",
            name: "Alien Googah",
            grade: "Alien",
            avatar: "https://rickandmortyapi.com/api/character/avatar/13.jpeg",
            comment: "",
            tags: "unknown,unknown ,",
            contact: "Earth (Replacement Dimension)",
            link: "https://rickandmortyapi.com/api/location/20",
          },
        ],
      },
      {
        title: "Оффер",
        type: Stages.offer,
        list: [],
      },
    ],
  },
];
